export const acceptedBrands = {
  AMEX: ['AMERICAN EXPRESS', 'AMERICAN EXPRESS COMPANY'],
  DINERS: ['DINERS CLUB INTERNATIONAL'],
  DISCOVER: ['DISCOVER'],
  ELO: ['ELO'],
  HIPERCARD: ['HIPERCARD'],
  MASTER: ['MAESTRO', 'MASTERCARD'],
  OUROCARD: ['OUROCARD'],
  VISA: ['VISA'],
  DEFAULT: ['VISA'],
};
